### ISSUE TITLE
Daphne not working with django-simple-task?

### ISSUE THREAD

**Issue by jillson** [ericls/django-simple-task#7]
If I run a fairly simple django app (which I'll try to get pushed to a sample repo on github at some point) that follows your instructions, when running the django app via Daphne, Daphne doesn't send a scope["type"] == lifetime event, and as a result, the queue/loop values don't get set, so when defer is called, the loop doesn't get used and the function just finishes (so the deferred "func" isn't called); swapping uvicorn for Daphne and django-simple-task works as advertised.  Reading quickly the ASGI spec, I _think_ Daphne isn't following the suggested lifetime bit, but I could be missing something.  Anyways, I would suggest:
A) If you've tested it with Daphne, documenting any extra steps required
B) If I'm correct and uvicorn is doing the asgi spec the way django-simple-task expects, recommend using that.
C) Modifying task.py's defer so that if loop isn't defined, it at least logs that there was no queue to save this func to run (or possibly just call the func inline?)

**Comment by ericls** [comment]
Thanks for your input.
Daphne does not currently support lifespan calls.
Let me do B) and C) as you suggested.

**Comment by ericls** [comment]
#8
